### ISSUE TITLE
incompatible with the <dialog> element

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/ember-velcro#122]
This is due to this here: https://github.com/floating-ui/floating-ui/issues/2496#issuecomment-1686187905

I think this library should _not_ add transforms for positioning, and should instead leave that to floating-ui.

**Comment by lukemelia** [comment]
@ynotdraw @NullVoxPopuli I understand why this change was made, but I think it would be more appropriate to allow the user to opt out of transforms. `transform` is the more performant way to position most HTML elements. floating-ui's vue implementation [defaults to using `transform`](https://github.com/floating-ui/floating-ui/blob/56d5e0f255459711fd3712c805ba03621fc86946/packages/vue/src/useFloating.ts#L45).

We could consider automatically opting for `top`/`left` or warning if the floating element is a `dialog`.

WDYT?

**Comment by NullVoxPopuli** [comment]
sounds good to me, seems fair to change behavior based off of element
