### ISSUE TITLE
Any plans to support "autoPlacement" instead of "flip" (maybe as an option)?

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/ember-velcro#96]
Was reading through the docs and flip and autoPlacement can't be used at the same time: https://floating-ui.com/docs/autoPlacement#conflict-with-flip

so like, since flip is hard-coded, autoPlacement can't be used with ember-velcro atm

**Comment by NullVoxPopuli** [comment]
@ynotdraw @camskene ?

**Comment by ynotdraw** [comment]
Makes sense to me 👍 I'm curious what @camskene would say.

**Comment by camskene** [comment]
👋 @NullVoxPopuli 😃

**Comment by camskene** [comment]
@NullVoxPopuli @ynotdraw I do remember I had to _choose_ between those options but don't recall why I went with flip. Supporting autoplacement as an option would be great.
